# Nhost Project Configuration
# https://docs.nhost.io/reference/config

subdomain = "ronqbmjmmogmskjtfjym"
region = "ap-south-1"

[global]
node_version = "20"

[auth]
version = "2.29.0"

[graphql]
version = "2.40.0"

[postgres]
version = "14.10"
